language: csharp

mono: none
dotnet: 5.0.202
sudo: false

env: 
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_script:
    - dotnet restore

script: 
    - dotnet build PsuHistoryWeb.sln -c Release
    #- dotnet test -c Release --no-build BllTest/BllTest.fsproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

#after_script:
#    - bash <(curl -s https://codecov.io/bash)